Combine workflows

diff --git a/.github/workflows/icon-review.yml b/.github/workflows/icon-review.yml
--- a/.github/workflows/icon-review.yml
+++ b/.github/workflows/icon-review.yml
@@ -35,12 +35,38 @@ jobs:
           path: main
           persist-credentials: false
 
-      - name: Review SVG files 🔍
+      - name: Get changed SVG file names 📄
         run: |
           cd main
           svgFiles=$(git diff --no-index ../main ../fork --diff-filter=ACMRTUX --name-only | grep '.svg$')
-          echo "SVG files changed: ${svgFiles}"
-          npx svg-icon-review --bigIcon ${svgFiles}
+          echo "Changed SVG files: $svgFiles"
+          echo "SVG_FILES=${svgFiles}" >> $GITHUB_ENV
+
+      - name: Check SVG colors
+        id: color_check
+        run: |
+          cd main
+          set -o pipefail
+          echo "COLOR_CHECK_OUTPUT=$(npx svg-color-linter --colors material-colors.yml ${{env.SVG_FILES}})" >> $GITHUB_ENV
+
+      - name: Color check failed 📢
+        if: failure()
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `## Failure 🚨\n\nSome of the icons use an invalid color. More details:\n\n\`\`\`\n${{env.COLOR_CHECK_OUTPUT}}\n\`\`\`\n\nPlease refer to the [contribution guidelines](https://github.com/material-extensions/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#material-design-colors) for more information.`
+            });
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Generate Icon Preview
+        run: |
+          cd main
+          npx svg-icon-review --bigIcon ${{env.SVG_FILES}})
 
       - name: Install jq ⚙️
         run: sudo apt-get install jq
@@ -60,7 +86,7 @@ jobs:
           script: |
             const image_url = "${{ env.image_url }}";
             console.log('URL: '+image_url);
-            const commentBody = '## Preview \n\nThank you for creating a pull request. This preview shows you how your changes will look on the different themes: \n\n ![Generated Preview](' + image_url + ') \n\n You can find more information how to contribute in the [contribution guidelines](https://github.com/material-extensions/vscode-material-icon-theme/blob/main/CONTRIBUTING.md).';
+            const commentBody = '## Preview \n\nThis preview shows you how your changes will look on the different themes: \n\n ![Generated Preview](' + image_url + ') \n\n You can find more information how to contribute in the [contribution guidelines](https://github.com/material-extensions/vscode-material-icon-theme/blob/main/CONTRIBUTING.md).';
 
             github.rest.issues.createComment({
               issue_number: context.issue.number,
